# define the cpu used by the saml21 board
export CPU = saml21
export CPU_MODEL = saml21j18a
export CPU_FAM_SUB = saml21

# setup serial terminal
PORT_LINUX ?= /dev/ttyACM0
include $(RIOTMAKE)/tools/serial.inc.mk

# this board uses openocd
include $(RIOTMAKE)/tools/openocd.inc.mk
